/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-12-17 10:57:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastrarProduto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Cadastro de produto</title>\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap/js/bootstrap.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("\t\r\n");
      out.write("\t\tbody,html{\r\n");
      out.write("\t\t\theight:100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("        body {\r\n");
      out.write("            background-image:url(./img/plano2.jpg);  \r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("               \r\n");
      out.write("\t\tinput[type=text]:hover, textarea:hover{ \r\n");
      out.write("\t      \tborder:1px solid rgba(219, 140, 83, 0.9);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t#escritaCadProd {\r\n");
      out.write("\t\t\tfont-family: Verdana, Geneva, Tahoma, sans-serif;\r\n");
      out.write("            font-size: 4vh;\r\n");
      out.write("            color: white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.c{\r\n");
      out.write("\t\t\tbox-shadow:3px 2px 8px 2px rgb(59,57, 57);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"adm.jsp\" id=\"escola\" style=\"color: white;\">CONTROLE</a>\r\n");
      out.write("                    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                      <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                   </button>\r\n");
      out.write("          \r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            \r\n");
      out.write("                  <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                      <a class=\"nav-link\" href=\"cadastraUser.jsp\" style=\"color: white;\">Cadastrar User</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                      <a class=\"nav-link\" href=\"controleUser.jsp\" style=\"color: white;\">Controle de Usuario</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"nav-item\">\r\n");
      out.write("                      <a class=\"nav-link\" href=\"controleProduto.jsp\" style=\"color: white;\">Controle de produtos</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                  </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container mt-5\">           \r\n");
      out.write("        <div class=\"row \">\r\n");
      out.write("   \t\t\t<div class=\"col-8\">\r\n");
      out.write("   \t\t\t\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("   \t\t\t<div class=\"col-lg-4 col-sm-12\">\r\n");
      out.write("   \t\t\t\t<div class=\"card c\">\r\n");
      out.write("   \t\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("   \t\t\t\t\t\t<h5>Cadastrar produto</h1>\r\n");
      out.write("   \t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("   \t\t\t\t\t\t<form method=\"get\" action=\"Processa\">\r\n");
      out.write("   \t\t\t\t\t\t\r\n");
      out.write("   \t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t<label>Tipo</label>\r\n");
      out.write("   \t\t\t\t\t\t\t\t<select name=\"tipoProd\" class=\"form-control\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t<option value=\"selecione\" disabled selected >Qual o tipo?</option>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t<option value=\"lanche\">Lanche</option>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t<option value=\"porcao\">Porção</option>\r\n");
      out.write("   \t\t\t\t\t\t\t\t\t<option value=\"bebida\">Bebida</option>\r\n");
      out.write("   \t\t\t\t\t\t\t\t</select>\r\n");
      out.write("   \t\t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\t\t\r\n");
      out.write("   \t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t<label>Nome</label>\r\n");
      out.write("   \t\t\t\t\t\t\t\t<input type=\"text\" name=\"nomeProd\" class=\"form-control\">\r\n");
      out.write("   \t\t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t<label>Descrição</label>\r\n");
      out.write("   \t\t\t\t\t\t\t\t<input type=\"text\" name=\"descricaoProd\" class=\"form-control\">\r\n");
      out.write("   \t\t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\r\n");
      out.write("   \t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("   \t\t\t\t\t\t\t\t<label>Preço</label>\r\n");
      out.write("   \t\t\t\t\t\t\t\t<input type=\"text\" name=\"precoProd\" class=\"form-control\">\r\n");
      out.write("   \t\t\t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\t\t\t<input type=\"hidden\" name=\"acao\" value=\"cadastrarProduto\">\r\n");
      out.write("   \t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-danger btn-block\">\r\n");
      out.write("   \t\t\t\t\t\t</form>\r\n");
      out.write("   \t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t</div>\r\n");
      out.write("   \t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
